#include<iostream>
#include<cstdio>
#include<cstring>
using namespace std;

int main()
{
    char s[100][200];
    int a,b,c,d,n,num[30],i,j,sum=0,cnt=0,tmpcnt=0;
    scanf("%d%d%d%d%d",&a,&b,&c,&d,&n);
    for(i=0;i<n;i++){scanf("%d",num+i);sum+=num[i];}
    if(a*b+c*d!=sum){printf("NO\n");goto label;}
    printf("YES\n");
    if(b>d)
    {
        for(i=d;i<b;i++)
            for(j=a;j<a+c;j++)
                s[i][j]='.';       
    }
    else
    {
        for(i=b;i<d;i++)
            for(j=0;j<a;j++)
                s[i][j]='.';    
    }
    if(a&1)
    {
        for(i=0;i<a;i++)
        {
            if(i&1)
                for(j=0;j<b;j++)
                {
                    s[j][i]=cnt+'a';
                    tmpcnt++;
                    if(tmpcnt==num[cnt])
                    {
                        tmpcnt=0;
                        cnt++;                  
                    }
                }
            else
                for(j=b-1;j>=0;j--)
                {
                    s[j][i]=cnt+'a';
                    tmpcnt++;
                    if(tmpcnt==num[cnt])
                    {
                        tmpcnt=0;
                        cnt++;                  
                    }
                }
        }
        for(i=a;i<a+c;i++)
        {
            if(i&1)
                for(j=0;j<d;j++)
                {
                    s[j][i]=cnt+'a';
                    tmpcnt++;
                    if(tmpcnt==num[cnt])
                    {
                        tmpcnt=0;
                        cnt++;                  
                    }
                }
            else
                for(j=d-1;j>=0;j--)
                {
                    s[j][i]=cnt+'a';
                    tmpcnt++;
                    if(tmpcnt==num[cnt])
                    {
                        tmpcnt=0;
                        cnt++;                  
                    }
                }
        }       
    }
    else
    {
        for(i=0;i<a;i++)
        {
            if(!(i&1))
                for(j=0;j<b;j++)
                {
                    s[j][i]=cnt+'a';
                    tmpcnt++;
                    if(tmpcnt==num[cnt])
                    {
                        tmpcnt=0;
                        cnt++;                  
                    }
                }
            else
                for(j=b-1;j>=0;j--)
                {
                    s[j][i]=cnt+'a';
                    tmpcnt++;
                    if(tmpcnt==num[cnt])
                    {
                        tmpcnt=0;
                        cnt++;                  
                    }
                }
        }
        for(i=a;i<a+c;i++)
        {
            if(!(i&1))
                for(j=0;j<d;j++)
                {
                    s[j][i]=cnt+'a';
                    tmpcnt++;
                    if(tmpcnt==num[cnt])
                    {
                        tmpcnt=0;
                        cnt++;                  
                    }
                }
            else
                for(j=d-1;j>=0;j--)
                {
                    s[j][i]=cnt+'a';
                    tmpcnt++;
                    if(tmpcnt==num[cnt])
                    {
                        tmpcnt=0;
                        cnt++;                  
                    }
                }
        }       
    }
    for(i=0;i<(b>d?b:d);i++)printf("%s\n",s[i]);
    label:;
    //system("pause");
    return 0;
}
