#include<iostream>
#include<cstdio>
#include<cstring>
#include<algorithm>
using namespace std;
int a[200005];
int main()
{
    int n,m,i,mm,nn,cnt1,cnt2,c1,c2;
    scanf("%d%d",&m,&n);
    mm=m,nn=n;
    a[0]=0;
    mm--;
    for(i=1;i<m+n;i++)
    {
        if(i&1)
        {
            if(a[i-1])
            {
                if(mm)
                {
                    mm--;
                    a[i]=0;
                }
                else
                {
                    nn--;
                    a[i]=1;
                }
            }
            else
            {
                if(nn)
                {
                    nn--;
                    a[i]=1;
                }
                else
                {
                    mm--;
                    a[i]=0;
                }
            }
        }
        else
        {
            if(a[i-1])
            {
                if(nn)
                {
                    nn--;
                    a[i]=1;
                }
                else
                {
                    mm--;
                    a[i]=0;
                }
            }
            else
            {
                if(mm)
                {
                    mm--;
                    a[i]=0;
                }
                else
                {
                    nn--;
                    a[i]=1;
                }
            }
        }
    }
    cnt1=cnt2=0;
    for(i=1;i<m+n;i++)
    {
        if(a[i]==a[i-1])cnt1++;
        else cnt2++;
    }
    c1=cnt1;
    c2=cnt2;
    mm=m;nn=n;
    a[0]=1;
    nn--;
    for(i=1;i<m+n;i++)
    {
        if(i&1)
        {
            if(a[i-1])
            {
                if(mm)
                {
                    mm--;
                    a[i]=0;
                }
                else
                {
                    nn--;
                    a[i]=1;
                }
            }
            else
            {
                if(nn)
                {
                    nn--;
                    a[i]=1;
                }
                else
                {
                    mm--;
                    a[i]=0;
                }
            }
        }
        else
        {
            if(a[i-1])
            {
                if(nn)
                {
                    nn--;
                    a[i]=1;
                }
                else
                {
                    mm--;
                    a[i]=0;
                }
            }
            else
            {
                if(mm)
                {
                    mm--;
                    a[i]=0;
                }
                else
                {
                    nn--;
                    a[i]=1;
                }
            }
        }
    }
    cnt1=cnt2=0;
    for(i=1;i<m+n;i++)
    {
        if(a[i]==a[i-1])cnt1++;
        else cnt2++;
    }
    if(cnt1>c1)
    {
        c1=cnt1;
        c2=cnt2;
    }
    printf("%d %d\n",c1,c2);
    return 0;
}
